### ISSUE TITLE
Icehouse

### ISSUE THREAD

**Issue by LordBrain** [rochaporto/dashing-openstack#7]
I see that this project is kind of old. I am having problems getting the dashboard up for my Icehouse openstack instance. Should it work for that version?

What are all the things that need to be configured?

I am getting this error when running dashing:
scheduler caught exception:
845: NaN not allowed in JSON
/var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:125:in `to_json'
/var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:125:in`send_event'
/home/dashing/dashing-openstack/jobs/openstack.rb:157:in `block (2 levels) in <top (required)>'
/home/dashing/dashing-openstack/jobs/openstack.rb:138:in`each'
/home/dashing/dashing-openstack/jobs/openstack.rb:138:in `block in <top (required)>'

Any idea what to check?

**Comment by rochaporto** [comment]
Hi.

I won't be able to try it out in the next couple weeks, but check the config.yaml and aviator.yaml files. The values to be filled should be more or less obvious... from the error it seems to be failing to contact keystone.

Will try to help anyway.

**Comment by LordBrain** [comment]
So I did some hacking on it and tracked my problem down to the if sorted_tenants.length > 5 section of the openstack.rb.
In my system I have 6 tenants, and all of them are showing up in the dashboard just fine. But I think the way ruby is parsing the array, the .length, shows up as 6 so it tries to do that part of the code when in reality it done it in the section above, sorted_tenants[0..5]. I think the code needs to be changed to sorted_tenants.length > 6, but for me I just commented it out to get past it.
