### ISSUE TITLE
How to show all tenant

### ISSUE THREAD

**Issue by jkhelil** [rochaporto/dashing-openstack#8]
I use admin user wich have admin role only on admin tenant, but keystone does not fetch all tenant, so I can not see tenants on the dashboard. Is there a way to tell aviator to use admin URL.

**Comment by visibilityspots** [comment]
@jkhelil did you found a solution for this in the meantime cause right now I'm stuck on this issue too..

**Comment by jkhelil** [comment]
@visibilityspots  sorry no

**Comment by visibilityspots** [comment]
@rochaporto for some reason I get this error when running the job:

``` bash
/home/vagrant/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/generic.rb:1203:in `rescue in merge': the scheme http does not accept registry part: 192.168.91.11:9696v2.0 (or bad hostname?) (URI::InvalidURIError)
    from /home/vagrant/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/generic.rb:1200:in `merge'
    from /home/vagrant/.rvm/gems/ruby-2.1.2@aviatordemo/gems/faraday-0.8.8/lib/faraday/connection.rb:303:in `build_exclusive_url'
    from /home/vagrant/.rvm/gems/ruby-2.1.2@aviatordemo/gems/faraday-0.8.8/lib/faraday/request.rb:94:in `to_env'
    from /home/vagrant/.rvm/gems/ruby-2.1.2@aviatordemo/gems/faraday-0.8.8/lib/faraday/connection.rb:252:in `run_request'
    from /home/vagrant/.rvm/gems/ruby-2.1.2@aviatordemo/gems/faraday-0.8.8/lib/faraday/connection.rb:106:in `get'
    from /home/vagrant/.rvm/gems/ruby-2.1.2@aviatordemo/bundler/gems/aviator-d7c9c217f097/lib/aviator/core/service.rb:85:in `request'
    from openstack-manual.rb:49:in `get_tenant_data'
    from openstack-manual.rb:136:in `block in <main>'
    from openstack-manual.rb:135:in `each'
    from openstack-manual.rb:135:in `<main>'
```

It's not clear to me where he gets that uri from since it seems like a / is missing somewhere..
